version: "3.9"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-2
      - MP_PUBLIC_KEY=
      - MP_ACCESS_TOKEN=
    restart: always
