FROM php:8.2-cli

# Instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libzip-dev \
    && docker-php-ext-install zip

# Instalar Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

# Copia seu projeto para o container
COPY . /app

# Instala dependências PHP
RUN composer install

# Comando padrão do worker
CMD ["php", "worker.php"]
